import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "Landingpage/**",
      "node_modules/**",
      ".next/**",
      "dist/**",
      // Generated test output. `coverage/` is gitignored, but ESLint does not read .gitignore,
      // so the v8 HTML report was being linted and reporting its own unused-disable comments.
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "e2e-report/**",
    ],
  },
  {
    files: ["src/features/**/*.{ts,tsx}"],
    rules: {
      // DoD Phase 03: features must consume design tokens (globals.css / token-doc),
      // never inline brand hex or rgba colour literals.
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value=/^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/]",
          message:
            "Hardcoded hex colour in features. Use a token from globals.css/token-doc instead.",
        },
        {
          selector:
            "TemplateLiteral > TemplateElement[value.cooked=/^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/]",
          message:
            "Hardcoded hex colour in features. Use a token from globals.css/token-doc instead.",
        },
        {
          selector: "Literal[value=/^rgba?\\((\\s*[0-9.]+(\\s*%?)\\s*,){3}[0-9./\\s%]+\\)$/]",
          message: "Hardcoded colour in features. Use a token from globals.css/token-doc instead.",
        },
      ],
    },
  },
  {
    // next-env.d.ts is regenerated by Next.js (typed routes triple-slash ref) —
    // the generated reference is not something lint should enforce on.
    files: ["next-env.d.ts"],
    rules: {
      "@typescript-eslint/triple-slash-reference": "off",
    },
  },
  {
    // Metro reads `metro.config.js` itself as CommonJS, so `require()` and `module.exports` are
    // the only working syntax there — the package is not `"type": "module"`, and rewriting it to ESM
    // imports makes Metro fail to load the config at all.
    files: ["apps/mobile/metro.config.js", "apps/mobile/babel.config.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  {
    // `eslint-plugin-react-hooks` reaches this config transitively, through `eslint-config-next`,
    // and the resolved major is not the same on every machine: a pnpm install gives v5 (two rules)
    // while Netlify's build image gives v7 (the React Compiler rules). Both are accepted here
    // deliberately, because the alternative is a rule set that depends on the installer — and a
    // build that only fails on the deploy.
    //
    // These two files read an external system (the Notification API, the OS scheduler) and write
    // the answer to state from an async callback, which is what effects are for; v7 flags the call
    // because it cannot see the `await` that stands between the effect and the write. The
    // exemption is stated here rather than in a comment so it survives both plugin versions: an
    // `eslint-disable` line naming a rule the installed plugin does not have is itself an error.
    files: [
      "src/features/notifications/PushOptIn.tsx",
      "apps/mobile/src/hooks/use-reminder-sync.ts",
    ],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
];

export default eslintConfig;
