import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: ["Landingpage/**", "node_modules/**", ".next/**", "dist/**"],
  },
  {
    files: ["src/features/**/*.{ts,tsx}"],
    rules: {
      // DoD Phase 03: features must consume design tokens (globals.css / token-doc),
      // never inline brand hex or rgba colour literals.
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value=/^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/]",
          message:
            "Hardcoded hex colour in features. Use a token from globals.css/token-doc instead.",
        },
        {
          selector: 'TemplateLiteral > TemplateElement[value.cooked=/^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/]',
          message:
            "Hardcoded hex colour in features. Use a token from globals.css/token-doc instead.",
        },
        {
          selector: "Literal[value=/^rgba?\\((\\s*[0-9.]+(\\s*%?)\\s*,){3}[0-9./\\s%]+\\)$/]",
          message:
            "Hardcoded colour in features. Use a token from globals.css/token-doc instead.",
        },
      ],
    },
  },
  {
    // next-env.d.ts is regenerated by Next.js (typed routes triple-slash ref) —
    // the generated reference is not something lint should enforce on.
    files: ["next-env.d.ts"],
    rules: {
      "@typescript-eslint/triple-slash-reference": "off",
    },
  },
];

export default eslintConfig;