import { z } from "zod";

import {
  accounts,
  adherenceDaily,
  aiInsights,
  caregiverAlerts,
  caregiverInvitations,
  caregiverRelationships,
  demoStates,
  doseActions,
  doseEvents,
  DOSE_ACTIONS,
  DOSE_EVENT_STATUSES,
  medicationSchedules,
  medications,
  MEDICATION_STATUSES,
  notifications,
  NOTIFICATION_TYPES,
  sessions,
  users,
  userPreferences,
  verifications,
} from "./schema";

/* Phase 05 zod mirrors of the §8 row insert types. One per table, validated against an
   insert-typed demo row in `seed.test.ts` (spec: "a test asserts every table has a
   zod-validated insert demo row"). Business validation belongs to Phase 07 — these only
   mirror the schema layer. */

const ts = z.date();
const tsOpt = ts.nullable().optional();

export interface InsertSchemaEntry {
  name: string;
  schema: z.ZodType;
  demoRow: unknown;
}

export const INSERT_SCHEMAS: InsertSchemaEntry[] = [
  {
    name: "users",
    schema: z.object({
      id: z.string(),
      name: z.string(),
      email: z.string().email(),
      emailVerified: z.boolean().optional(),
      image: z.string().nullable().optional(),
      timezone: z.string().optional(),
      onboardingCompleted: z.boolean().optional(),
      isDemo: z.boolean().optional(),
    }),
    demoRow: {
      id: "user-demo",
      name: "Arun Kumar",
      email: "demo@medvault.local",
      timezone: "Asia/Kolkata",
      onboardingCompleted: true,
      isDemo: true,
    } satisfies typeof users.$inferInsert,
  },
  {
    name: "session",
    schema: z.object({
      id: z.string(),
      token: z.string(),
      userId: z.string(),
      expiresAt: ts,
      ipAddress: z.string().nullable().optional(),
      userAgent: z.string().nullable().optional(),
      email: z.string().nullable().optional(),
      updatedAt: tsOpt,
    }),
    demoRow: {
      id: "session-demo",
      token: "tok_demo",
      userId: "user-demo",
      expiresAt: new Date(),
      ipAddress: "127.0.0.1",
    } satisfies typeof sessions.$inferInsert,
  },
  {
    name: "account",
    schema: z.object({
      id: z.string(),
      accountId: z.string(),
      providerId: z.string(),
      userId: z.string(),
      accessToken: z.string().nullable().optional(),
      refreshToken: z.string().nullable().optional(),
      idToken: z.string().nullable().optional(),
      accessTokenExpiresAt: tsOpt,
      refreshTokenExpiresAt: tsOpt,
      scope: z.string().nullable().optional(),
      password: z.string().nullable().optional(),
    }),
    demoRow: {
      id: "account-demo",
      accountId: "demo-account",
      providerId: "credential",
      userId: "user-demo",
    } satisfies typeof accounts.$inferInsert,
  },
  {
    name: "verification",
    schema: z.object({
      id: z.string(),
      identifier: z.string(),
      value: z.string(),
      expiresAt: ts,
      updatedAt: tsOpt,
    }),
    demoRow: {
      id: "verification-demo",
      identifier: "demo@medvault.local",
      value: "abc123",
      expiresAt: new Date(),
    } satisfies typeof verifications.$inferInsert,
  },
  {
    name: "medications",
    schema: z.object({
      id: z.string(),
      userId: z.string(),
      name: z.string(),
      dosageAmount: z.string(),
      dosageUnit: z.string(),
      instructions: z.string().nullable().optional(),
      notes: z.string().nullable().optional(),
      status: z.enum(MEDICATION_STATUSES).optional(),
      startDate: z.string(),
      endDate: z.string().nullable().optional(),
      color: z.string().optional(),
      remindersEnabled: z.boolean().optional(),
      archivedAt: tsOpt,
    }),
    demoRow: {
      id: "med-metformin",
      userId: "user-demo",
      name: "Metformin",
      dosageAmount: "500",
      dosageUnit: "mg",
      status: "active",
      startDate: "2026-09-01",
      color: "#10b981",
    } satisfies typeof medications.$inferInsert,
  },
  {
    name: "medication_schedules",
    schema: z.object({
      id: z.string(),
      medicationId: z.string(),
      timeOfDay: z.string(),
      daysOfWeek: z.array(z.number()).optional(),
      dosageAmount: z.string().nullable().optional(),
      instructionOverride: z.string().nullable().optional(),
      enabled: z.boolean().optional(),
    }),
    demoRow: {
      id: "slot-met-am",
      medicationId: "med-metformin",
      timeOfDay: "08:00",
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    } satisfies typeof medicationSchedules.$inferInsert,
  },
  {
    name: "dose_events",
    schema: z.object({
      id: z.string(),
      userId: z.string(),
      medicationId: z.string(),
      scheduleId: z.string().nullable().optional(),
      scheduledFor: ts,
      status: z.enum(DOSE_EVENT_STATUSES).optional(),
      missedDeadline: tsOpt,
      takenAt: tsOpt,
      skippedAt: tsOpt,
      skippedReason: z.string().nullable().optional(),
      snoozeCount: z.number().optional(),
      snoozeUntil: tsOpt,
      isDemo: z.boolean().optional(),
      source: z.enum(["generated", "demo"]).optional(),
    }),
    demoRow: {
      id: "dose-demo",
      userId: "user-demo",
      medicationId: "med-metformin",
      scheduledFor: new Date(),
      status: "upcoming",
      isDemo: true,
      source: "demo",
    } satisfies typeof doseEvents.$inferInsert,
  },
  {
    name: "dose_actions",
    schema: z.object({
      id: z.string(),
      userId: z.string(),
      doseEventId: z.string(),
      action: z.enum(DOSE_ACTIONS),
      occurredAt: ts,
      meta: z.unknown().nullable().optional(),
    }),
    demoRow: {
      id: "action-demo",
      userId: "user-demo",
      doseEventId: "dose-demo",
      action: "take",
      occurredAt: new Date(),
      meta: { source: "demo" },
    } satisfies typeof doseActions.$inferInsert,
  },
  {
    name: "adherence_daily",
    schema: z.object({
      id: z.string(),
      userId: z.string(),
      date: z.string(),
      medicationId: z.string().nullable().optional(),
      scheduled: z.number().optional(),
      taken: z.number().optional(),
      missed: z.number().optional(),
      skipped: z.number().optional(),
      snoozed: z.number().optional(),
      adherencePercent: z.string().nullable().optional(),
      streakDay: z.boolean().optional(),
    }),
    demoRow: {
      id: "adh-demo",
      userId: "user-demo",
      date: "2026-09-10",
      scheduled: 5,
      taken: 5,
      missed: 0,
      skipped: 0,
      snoozed: 0,
      adherencePercent: "100.00",
      streakDay: true,
    } satisfies typeof adherenceDaily.$inferInsert,
  },
  {
    name: "caregiver_relationships",
    schema: z.object({
      id: z.string(),
      patientUserId: z.string(),
      caregiverUserId: z.string(),
      status: z.enum(["pending", "active", "declined", "revoked"]).optional(),
      relationType: z.enum(["family", "friend", "professional", "other"]).optional(),
      permissions: z.unknown().nullable().optional(),
      invitedByUserId: z.string().nullable().optional(),
      revokedAt: tsOpt,
      acceptedAt: tsOpt,
    }),
    demoRow: {
      id: "rel-demo",
      patientUserId: "user-demo",
      caregiverUserId: "user-caregiver",
      status: "active",
      relationType: "family",
    } satisfies typeof caregiverRelationships.$inferInsert,
  },
  {
    name: "caregiver_invitations",
    schema: z.object({
      id: z.string(),
      patientUserId: z.string(),
      email: z.string().email(),
      token: z.string(),
      message: z.string().nullable().optional(),
      status: z.enum(["pending", "accepted", "expired", "revoked"]).optional(),
      expiresAt: ts,
    }),
    demoRow: {
      id: "inv-demo",
      patientUserId: "user-demo",
      email: "caregiver@medvault.local",
      token: "invite_token_demo",
      expiresAt: new Date(),
    } satisfies typeof caregiverInvitations.$inferInsert,
  },
  {
    name: "caregiver_alerts",
    schema: z.object({
      id: z.string(),
      patientUserId: z.string(),
      caregiverUserId: z.string(),
      relationshipId: z.string().nullable().optional(),
      doseEventId: z.string().nullable().optional(),
      type: z.enum(["missed_dose", "adherence_drop", "insight", "demo"]),
      title: z.string(),
      body: z.string(),
      data: z.unknown().nullable().optional(),
      status: z.enum(["new", "acknowledged", "resolved"]).optional(),
      resolvedAt: tsOpt,
    }),
    demoRow: {
      id: "alert-demo",
      patientUserId: "user-demo",
      caregiverUserId: "user-caregiver",
      type: "missed_dose",
      title: "Missed dose",
      body: "Metformin was missed.",
      status: "new",
    } satisfies typeof caregiverAlerts.$inferInsert,
  },
  {
    name: "notifications",
    schema: z.object({
      id: z.string(),
      userId: z.string(),
      type: z.enum(NOTIFICATION_TYPES),
      title: z.string(),
      body: z.string(),
      entityType: z.string().nullable().optional(),
      entityId: z.string().nullable().optional(),
      readAt: tsOpt,
    }),
    demoRow: {
      id: "notif-demo",
      userId: "user-demo",
      type: "missed_dose",
      title: "Dose missed",
      body: "You missed Metformin.",
      entityType: "doseEvent",
      entityId: "dose-demo",
    } satisfies typeof notifications.$inferInsert,
  },
  {
    name: "ai_insights",
    schema: z.object({
      id: z.string(),
      userId: z.string(),
      category: z.enum([
        "timing_pattern",
        "adherence_decline",
        "adherence_improvement",
        "snooze_pattern",
        "medication_difference",
        "missed_analysis",
        "general",
      ]),
      summary: z.string(),
      detail: z.string().nullable().optional(),
      suggestedActionType: z
        .enum(["review_schedule", "review_reminders", "encourage", "review_caregiver"])
        .nullable()
        .optional(),
      dataSnapshot: z.unknown(),
      source: z.enum(["ai", "fallback", "demo"]),
      confidence: z.string().nullable().optional(),
    }),
    demoRow: {
      id: "insight-demo",
      userId: "user-demo",
      category: "missed_analysis",
      summary: "Evening doses often missed",
      dataSnapshot: { range: "14d" },
      source: "demo",
      confidence: "90.40",
    } satisfies typeof aiInsights.$inferInsert,
  },
  {
    name: "user_preferences",
    schema: z.object({
      userId: z.string(),
      theme: z.enum(["light", "dark", "system"]).optional(),
      missedAfterMinutes: z.number().optional(),
      snoozeMinutes: z.number().optional(),
      maxSnoozes: z.number().optional(),
      reminderBeforeMinutes: z.number().optional(),
      notificationPrefs: z.unknown().optional(),
      caregiverAlertPrefs: z.unknown().optional(),
      reduceMotion: z.boolean().optional(),
      uiDensity: z.enum(["comfortable", "compact"]).optional(),
    }),
    demoRow: {
      userId: "user-demo",
      theme: "system",
      notificationPrefs: { doseReminders: true, caregiverMissedAlerts: true, insights: true, sounds: true },
      caregiverAlertPrefs: { missedDoseOn: true, adherenceDropThreshold: null, dailyDigest: false },
    } satisfies typeof userPreferences.$inferInsert,
  },
  {
    name: "demo_state",
    schema: z.object({
      id: z.string(),
      userId: z.string(),
      simulationNow: tsOpt,
      timeMultiplier: z.number().optional(),
      scenario: z.enum(["baseline", "decline", "improvement", "caregiver_demo"]).optional(),
      hasCaregiverDemoData: z.boolean().optional(),
    }),
    demoRow: {
      id: "demo-state",
      userId: "user-demo",
      timeMultiplier: 1,
      scenario: "baseline",
      hasCaregiverDemoData: false,
    } satisfies typeof demoStates.$inferInsert,
  },
];